# Generated by Django 4.1 on 2023-06-11 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dinosaurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('dinosaur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dinosaurs.dinosaur')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='dinosaur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dinosaurs.dinosaur'),
        ),
        migrations.CreateModel(
            name='UserFavoriteDinosaurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('dinosaurs', models.ManyToManyField(related_name='user_favor', through='dinosaurs.Like', to='dinosaurs.dinosaur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_dinos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='user_favorite_dinosaurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='dinosaurs.userfavoritedinosaurs'),
        ),
    ]
